name: Lexyk
description: Boost your vocabulary with Lexyk! Lexyk is a simple and easy-to-use app that helps you learn new words and improve your vocabulary. With Lexyk, you can learn new words, improve your vocabulary by swiping through flashcards. Lexyk is perfect for students, professionals, and anyone who wants to improve their vocabulary. Download Lexyk today and start learning new words!
full_description: 'Thank you for using Lexyk!'
android:
iOS: false
web: false
screenshots:
  - 01-screenshot.png
  - 02-screenshot.png
  - 03-screenshot.png
  - 04-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
