name: Lexyk
description: Learn a language!
full_description: ''
android:
iOS: false
web: false
screenshots:
  - 01-screenshot.png
  - 02-screenshot.png
  - 03-screenshot.png
  - 04-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
