name: Neon Frame
description: Highlight screenshots you're sharing to social media - Instagram Stories, Reels, Twitter, LinkedIn, etc.
full_description: '<b>v1.1.0 (Feb 16, 2024)</b><br>
<br>- Added a new screen with sharing options once the image is exported
<br>- Improved an image processing. Export takes less time now
<br>- Added a new overview video to Google Play'
android: https://play.google.com/store/apps/details?id=com.mobiledevpro.neonframe.app&utm_source=landing
iOS: false
web: false
screenshots:
  - 0.png
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
